@backend_HostAddress = http://localhost:5289

### submit
POST {{backend_HostAddress}}/api/applications
Content-Type: application/json

{
  "firstName": "Charles",
  "lastName": "Babbage",
  "preferredName": "Charlie",
  "nsn": "1234567890",
  "email": "charles@example.com",
  "phone": "021 555 0100",
  "dateOfBirth": "2009-12-26",
  "gender": "male",
  "currentHighSchool": "Hillcrest High School",
  "yearLevel": "year13",

  "course": "English",
  "preferredTime": "saturday-am",

  "address": "1 Dorset Street",
  "suburb": "Marylebone",
  "city": "London",
  "postcode": "W1U4EE",
  "country": "United Kingdom",

  "emergencyContactName": "Ada Lovelace",
  "emergencyContactRelationship": "Aunt",
  "emergencyContactEmail": "ada@computer.com",
  "emergencyContactPhone": "021333000",

  "nextOfKinName": "Ada Lovelace",
  "nextOfKinRelationship": "Aunt",
  "nextOfKinEmail": "ada@computer.com",
  "nextOfKinPhone": "021333000"
}

###
POST {{backend_HostAddress}}/api/applications
Content-Type: application/json

{
  "firstName": "Charles",
  "lastName": "",
  "email": "not-an-email"
}

### list applications
GET {{backend_HostAddress}}/api/applications
Accept: application/json

### fetch application one
GET {{backend_HostAddress}}/api/applications/1
Accept: application/json


# enquiry form thingy ig
### submit enquiry
POST {{backend_HostAddress}}/api/enquiries
Content-Type: application/json

{
    "firstName": "The",
    "lastName": "Doctor",
    "email": "timeandrelativedimensioninspace@tardis.com",
    "phone": "07700 900461",
    "currentHighSchool": "Gallifreyian Time Lord Academy",
    "yearLevel": "year13",

    "course": "Chinese",
    "preferredTime": "tuesday-am",

    "enquiryNature": "Other",
    "otherEnquiry": "TARDIS Circuits",
    "enquiryText": "I mean, we don't need language courses when the TARDIS can translate for us, do we?"
}

### list enquiries
GET {{backend_HostAddress}}/api/enquiries
Accept: application/json

### fetch enquiry one
GET {{backend_HostAddress}}/api/enquiries/1
Accept: application/json

#i think this is okay???
#idk what the second POST was for, so i ignored it